Added mypy github action to check type annotations and mypy stub files [unitaryhack]
qir-alliance/pyqir pull request #127
Opened 2022-06-04 05:42 UTC by WingCode

closes #57

2022-06-08 11:51 UTC, WingCode commented
@idavis I have made the changes you have required.

2022-06-08 14:05 UTC, idavis requested changes

2022-06-08 14:05 UTC, idavis commented on eng/psakefile.ps1
> +        mypy "$($pyqir.parser.python_dir)" "$($pyqir.generator.python_dir)" "$($pyqir.evaluator.python_dir)"
In order for the build to fail, we have to check the exit code of `mypy`. `Invoke-LoggedCommand` builds on top of `exec` which will do this for us.
```suggestion
        Invoke-LoggedCommand -errorMessage "Please fix the above mypy errors" {
            mypy "$($pyqir.parser.python_dir)" "$($pyqir.generator.python_dir)" "$($pyqir.evaluator.python_dir)"
        }
```

2022-06-08 14:13 UTC, idavis requested changes

2022-06-08 14:13 UTC, idavis commented on .github/workflows/link_and_spell_check.yml
> +    shell: pwsh
The check isn't running, I think we need to move this to its own job with steps
```suggestion
  check-type-annotations:
    runs-on: ubuntu-latest
    name: "Check type annotations and mypy stub files"
    steps:
      - uses: actions/checkout@v3
      - name: "Run mypy"
        run: ./build.ps1 -t checkmypy
        shell: pwsh

```

2022-06-08 15:56 UTC, idavis commented
@WingCode mypy requiring the wheels to be built requires extra dependencies. We can try to set up the dependencies in the workflow, but I think it might be better to run it [like the docs](https://github.com/qir-alliance/pyqir/blob/main/.github/workflows/ci.yml#L117-L133). The docs copy the wheels from the arifacts and then run tools which run the wheels.

If we add a task after docs that uses the lines above, and changes the task target to run mypy, I think this will be much easier. What do you think?

2022-06-08 16:25 UTC, WingCode commented
Yes @idavis we can do that. We will have to rename [docs](https://github.com/qir-alliance/pyqir/blob/168135555a0cf4fc5b6e786b8c063497e70f3af2/.github/workflows/ci.yml#L117-L133) YAML key to denote it is docs+mypy lint

2022-06-08 16:55 UTC, idavis commented
@WingCode I meant copy those lines, paste, and rename the copied job and edit the build target.

2022-06-09 02:49 UTC, WingCode commented
@idavis The mypy linting is working as expected as per the logs of failing CI build. Thank you for your patience and support!
Should we fix the mypy lint errors as part of this PR or a different PR?

2022-06-09 15:15 UTC, idavis commented
@WingCode The mypy and docs were skipped because the first checks failed. I think we need to remove mypy from the checks list (`task checks -depends cargo-fmt, cargo-clippy, checkmypy`) - Because it depends on rebuild, running the first checks triggers a full build, but on the github actions steps we populate the wheelhouse before running the mypy check which bypasses the full rebuild. I think that once checkmypy is removed from the checks task that everything will work.

I agree that fixing mypy results are a separate task. I'll create an issue for it once the checks run so that we have actionable items.

2022-06-09 15:37 UTC, idavis requested changes

2022-06-09 15:37 UTC, idavis commented on eng/psakefile.ps1
> +task checks -depends cargo-fmt, cargo-clippy, checkmypy
```suggestion
task checks -depends cargo-fmt, cargo-clippy
```

2022-06-09 16:54 UTC, idavis approved these changes

2022-06-09 16:55 UTC, merged

2022-06-09 16:55 UTC, idavis commented
Thanks for the help @WingCode !